ALTER TABLE trips ADD COLUMN destination_airport VARCHAR(50) NOT NULL;
ALTER TABLE trips ADD COLUMN empty_weight FLOAT NOT NULL ;
ALTER TABLE trips ADD COLUMN departure_time TIMESTAMP NOT NULL;
ALTER TABLE trips ADD COLUMN arrival_time TIMESTAMP NOT NULL;
ALTER TABLE trips ADD COLUMN transit BOOLEAN NOT NULL;
ALTER TABLE trips ADD COLUMN comments VARCHAR(200);
ALTER TABLE trips ADD COLUMN passenger_id INTEGER NOT NULL;
ALTER TABLE trips ADD CONSTRAINT passenger_id_fkey FOREIGN KEY (passenger_id) REFERENCES persons(id);

